WIP: x86/fpu/signal: stop compiling code unused in 64bits-only mode
When there is no CONFIG_IA32_EMULATION, ia32_fxstate becomes a "false"
constant at compile-time and the bottom two thirds of
__fpu_restore_sig() are never run and generally optimized out. Add a
32bits #ifdef to stop trying to compile that 32bit-only code in 64
bits. This commit fixes compilation when that code is _not_ optimized
out with "CFLAGS_signal.o := $(CFLAGS) -Og"

  ld: vmlinux.o: in function `__fpu_restore_sig':
  signal.c:(.text+0x46503): undefined reference to `convert_to_fxsr'

Signed-off-by: Marc Herbert <marc.herbert@linux.intel.com>